name = "Catppuccin Mocha Unofficial"
author = "Pocco"
description = "An unofficial Catppuccin Mocha adaptation for TUI applications."

[colors]
# ------ Base
text = "#CDD6F4" # text
base = "#1E1E2E" # base

# ------ Surfaces
surface_0 = "#313244" # bg_2
surface_1 = "#45475A" # bg_3

# ------ Text
subtle = "#585B70" # surface_2
disabled = "#6C7086" # overlay_0

# ------ UI
border = "#6C7086" # overlay_0

# ------ Accents
accent = "#CBA6F7" # mauve
accent_2 = "#89B4FA" # blue
accent_3 = "#FAB387" # peach
accent_4 = "#A6E3A1" # green
accent_5 = "#F5C2E7" # pink

# ------ Semantic
success = "#A6E3A1" # green
warning = "#F9E2AF" # yellow
error = "#F38BA8" # red
info = "#89DCEB" # sky

# ------ Links
link = "#89B4FA" # blue

# ------ ANSI Palette
black = "#1E1E2E" # base
blue = "#667FA8" # new
green = "#769C72" # new
cyan = "#6D9E99" # new
red = "#B4546A" # new
magenta = "#9B78B8" # new
brown = "#B39A68" # new
light_gray = "#A6ADC8" # subtext_0

dark_gray = "#6C7086" # overlay_0
light_blue = "#89B4FA" # blue
light_green = "#A6E3A1" # green
light_cyan = "#94E2D5" # teal
light_red = "#F38BA8" # red
light_magenta = "#CBA6F7" # mauve
yellow = "#F9E2AF" # yellow
white = "#CDD6F4" # text