name = "Catppuccin Mocha Unofficial"
author = "Pocco"
description = "An unofficial Catppuccin Mocha adaptation for TUI applications."

[colors]
# ------ Base
text = "#CDD6F4"; # text
base = "#1E1E2E"; # base

# ------ Surfaces
surface_0 = "#313244"; # bg_2
surface_1 = "#45475A"; # bg_3

# ------ Text
muted = "#6C7086"; # overlay_0
subtle = "#585B70"; # surface_2
disabled = "#6C7086"; # overlay_0

# ------ UI
border = "#6C7086"; # overlay_0

# ------ Accents
accent = "#CBA6F7"; # mauve
accent_2 = "#89B4FA"; # blue
accent_3 = "#FAB387"; # peach
accent_4 = "#A6E3A1"; # green
accent_5 = "#F5C2E7"; # pink

# ------ Semantic
success = "#A6E3A1"; # green
warning = "#F9E2AF"; # yellow
error = "#F38BA8"; # red
info = "#89DCEB"; # sky

# ------ Links
link = "#89B4FA"; # blue

# ------ ANSI Palette
black = "#45475A"
blue = "#89B4FA"
green = "#A6E3A1"
cyan = "#94E2D5"
red = "#F38BA8"
magenta = "#F5C2E7"
brown = "#F9E2AF" # dark_yellow
light_gray = "#BAC2DE"

dark_gray = "#6C7086"
light_blue = "#89B4FA"
light_green = "#A6E3A1"
light_cyan = "#94E2D5"
light_red = "#F38BA8"
light_magenta = "#CBA6F7"
yellow = "#F9E2AF" # light_yellow
white = "#CDD6F4"